version: '3.8'

services:
  arangodb:
    image: arangodb:3.11
    container_name: law_search_arangodb
    restart: unless-stopped
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD:-password}
      ARANGO_NO_AUTH: 0
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    networks:
      - law_search_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8529/_api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: law_search_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DATABASE_URL=arangodb://root:${ARANGO_ROOT_PASSWORD:-password}@arangodb:8529
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      arangodb:
        condition: service_healthy
    networks:
      - law_search_network
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    container_name: law_search_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - law_search_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  arangodb_data:
    driver: local
  arangodb_apps:
    driver: local
  redis_data:
    driver: local

networks:
  law_search_network:
    driver: bridge
